version: '2'
services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=coin-project
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken
    volumes:
      - influxdb_data:/bitnami/influxdb
volumes:
  influxdb_data:
    driver: local
